name: Build

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/grogu.keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get Path Details
        run: |
             pwd
             tree -a
             ls -la /home/runner/work/_temp/keystore/grogu.keystore'

        
      - name: Compile
        run: ./gradlew app:build
        env:
          SAUCE_DEMO_STORE_FILE: '/home/runner/work/_temp/keystore/grogu.keystore'
          SAUCE_DEMO_KEY_ALIAS: ${{ secrets.SAUCE_DEMO_KEY_ALIAS }}
          SAUCE_DEMO_KEY_PASSWORD: ${{ secrets.SAUCE_DEMO_KEY_PASSWORD }}
          SAUCE_DEMO_STORE_PASSWORD: ${{ secrets.SAUCE_DEMO_STORE_PASSWORD }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
          TESTFAIRY_UPLOAD: ${{ secrets.TESTFAIRY_UPLOAD }}
          TESTFAIRY_TOKEN: ${{ secrets.TESTFAIRY_TOKEN }}
        shell: bash