name: Debug Workflow

on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    
    - name: Set Environment
      run: |
        printf "SAUCE_DEMO_STORE_FILE=%s/keystore/grogu.keystore" ${RUNNER_TEMP} >> ${GITHUB_ENV}



    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: ${{ env.SAUCE_DEMO_STORE_FILE }}
        encodedString: ${{ secrets.KEYSTORE }}


    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Print Env
      env:
        SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
        SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
        SAUCE_DEMO_KEY_ALIAS: ${{ secrets.SAUCE_DEMO_KEY_ALIAS }}
        SAUCE_DEMO_KEY_PASSWORD: ${{ secrets.SAUCE_DEMO_KEY_PASSWORD }}
        SAUCE_DEMO_STORE_PASSWORD: ${{ secrets.SAUCE_DEMO_STORE_PASSWORD }}
        TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
        TESTFAIRY_UPLOAD: 'TRUE'
      run: |
        echo ${{ secrets.SAUCE_USERNAME }} >> secrets.txt
        echo ${{ secrets.SAUCE_ACCESS_KEY }}  >> secrets.txt
        echo ${{ secrets.SAUCE_DEMO_KEY_ALIAS }}  >> secrets.txt
        echo ${{ secrets.SAUCE_DEMO_KEY_PASSWORD }}  >> secrets.txt
        echo ${{ secrets.SAUCE_DEMO_STORE_PASSWORD }}  >> secrets.txt
        echo ${{ secrets.TESTFAIRY_API_KEY }}  >> secrets.txt
        echo ${{ env.TESTFAIRY_UPLOAD }}  >> export.txt
        echo ${{ env.SAUCE_DEMO_STORE_FILE }}  >> export.txt
        echo ${{ env.SAUCE_DEMO_STORE_FILE }} >> export.txt
        echo 
        env >> env.txt
        pwd
        tree -a

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2