name: Publish APK

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/grogu.keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Detect version from release tag
        run: |
          echo "CI_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        shell: bash

      - name: Set app version and bump version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: ${{ env.CI_TAG }}

      - name: Compile APK
        run: |
          ./gradlew app:assembleDebug
          ./gradlew app:assembleDebugAndroidTest
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/mda-${{ env.CI_TAG }}-${{ github.run_number }}.apk
          mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk app/build/outputs/apk/debug/mda-androidTest-${{ env.CI_TAG }}-${{ github.run_number }}.apk
        env:
          SAUCE_DEMO_STORE_FILE: '/home/runner/work/_temp/keystore/grogu.keystore'
          SAUCE_DEMO_KEY_ALIAS: ${{ secrets.SAUCE_DEMO_KEY_ALIAS }}
          SAUCE_DEMO_KEY_PASSWORD: ${{ secrets.SAUCE_DEMO_KEY_PASSWORD }}
          SAUCE_DEMO_STORE_PASSWORD: ${{ secrets.SAUCE_DEMO_STORE_PASSWORD }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
          TESTFAIRY_UPLOAD: ${{ secrets.TESTFAIRY_UPLOAD }}
        shell: bash

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ env.CI_TAG }}
          tag_name: ${{ env.CI_TAG }}
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            app/build/outputs/apk/debug/mda-${{ env.CI_TAG }}-${{ github.run_number }}.apk
            app/build/outputs/apk/debug/mda-androidTest-${{ env.CI_TAG }}-${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}